### PR TITLE
Do not print quotemark if it is null

### PR DESCRIPTION
**Pull request by sfchen**
This is to provide a way to omit quotemark when output data.

The interface of  `writetable` is not changed, if `quotemark='\0'` is given in the parameter of `writetable()` function, then the quotemark is not printed.

This feature is very useful for outputing file formarts requring no quotemark, like VCF: http://samtools.github.io/hts-specs/VCFv4.1.pdf

VCF is heavily used in bioinformatics. And we shouldn't use quotemark for outputing VCF.

I have tested this change well with OpenGene.jl project (https://github.com/OpenGene/OpenGene.jl)

### CODE REVIEW

**Comment by nalimilan** [comment]
This makes it impossible to use `'\0'` as a quote mark, but I guess it's fine. Could you mention this in `docs/io.md`, though?

@tshort Should the Sphynx be updated too?

**Comment by sfchen** [comment]
Updated the doc. @nalimilan

**Comment by nalimilan** [comment]
Hmm, I'd rather say  ``Use `'\0'` to disable quotes`` or ``Use `'\0'` for no quote mark`` (your phrasing makes it sound like the `quotemark` variable is omitted, which doesn't make much sense). Could you also squash the two commits, so that we can merge after the feedback from Tom or others?

**Comment by johnmyleswhite** [comment]
Let's not use `'\0'` as a pun, especially given that there are data formats that `'\0'` as a field separator.

Analogies to the existing CSV printing code suggest that we should use something like `allowquotes` or `usequotes` to regulate the printing of quotemarks in a way that's orthogonal to the quotation character.

**Comment by sfchen** [comment]
Agreed @johnmyleswhite

**Comment by sfchen** [comment]
according to @johnmyleswhite , close this PR

**Comment by johnmyleswhite** [comment]
You don't need to close this PR, although it can't hurt to do so. It will show the updates to your code as you push them to GitHub.

**Comment by nalimilan** [comment]
Yeah, my first reaction was to add a separate boolean argument.

The name `allowquotes` doesn't make sense here. `usequotes` could do, but why not simply `quote`? This makes the pair `quote`/`quotemark` quite consistent.

**Comment by johnmyleswhite** [comment]
The trouble with `quote` is that it's both a noun and a verb, so you'll end up confused wondering why `quote != quotemark`.

**Comment by nalimilan** [comment]
Not a big deal I'd say, anyway those two arguments should appear side-by-side in the docs. `usequotes` doesn't sound great IMHO ("use for what?").

(Really, a `Nullable` with automated conversion from `Char` would be the best solution here, as discussed in several places already, but for now this isn't supported.)

**Pull request closed without merging**
