### PR TITLE
Speed up writetable

### PR DESCRIPTION
**Pull request by simonster**
This generates specialized code for `printtable` every set of column types, which speeds up the test case:

``` julia
make_testdf(n) = DataFrames.DataFrame(a=rand(1:typemax(Int), n), b=rand(1:typemax(Int), n), c=rand(1:typemax(Int), n), d=rand(1:typemax(Int), n), e=[randstring(10) for i = 1:n], f=[randstring(100) for i = 1:n], g=float64(rand(1:100, n)), h=[randstring(10) for i = 1:n], i=[randstring(10) for i = 1:n]);
df = make_testdf(2000000);
@time DataFrames.writetable("test.csv", df)
```

by about 25% on my system. I don't know if this is a good idea in general since it also means we have to compile specialized code for every size of DataFrame, but for DataFrames with many rows it's definitely advantageous. I still doubt we beat pandas, but in principle we could beat any implementation without a JIT for DataFrames with a sufficient number of rows.

After this change, writing the integer columns is the most expensive part, and without them there is now almost no allocation. (The allocation comes from `show(io, ::Int)`.) The second most expensive part is writing the strings in `print_escaped` from Base.

Ref JuliaLang/julia#7893

### CODE REVIEW

**Comment by quinnj** [comment]
`readtable` `writetable` are now deprecated

**Comment by nalimilan** [comment]
Though note that we [still have](https://github.com/JuliaStats/DataFrames.jl/blob/b293dd7268da844c0b0d61bb409937a3f6bd2b86/src/abstractdataframe/io.jl#L15) `printtable`, which is used by `show(io::IO, ::MIME"text/csv", df)`. Maybe we should get rid of it too, though.

**Comment by quinnj** [comment]
Yeah, I'm going to throw together a MarkdownTables.jl, HTMLTables.jl, and LatexTables.jl packages that these can live in (and be improved thru).

**Comment by nalimilan** [comment]
Please don't. These MD/HTML/LaTeX functions are very small and quite convenient. I wouldn't want to have to load a package just to format a data frame -- let alone the maintenance cost of coordinating all of these.

**Comment by rofinn** [comment]
I'd be in favour of moving them into separate packages if 1) they operated on an AbstractTable type that lived outside of DataFrames.jl and 2) we reexported them from DataFrames.jl.

**Comment by davidanthoff** [comment]
I've also been thinking about things like MarkdownTables.jl etc. (after seeing @quinnj talk about those at juliacon), and I think I'll almost certainly will create something like that in the iterable tables universe, so that folks can pipe queries and any table into such a format.

**Comment by quinnj** [comment]
Let's do it together! I can make the repos in JuliaData and they can depend on DataStreams as well as TableTraits.jl (I think that's the right iterable tables package?)

**Comment by nalimilan** [comment]
Why not make a single package which would support various formats? There are no external dependencies and the package will be very light. (BTW, that's LaTeX, not LaTex... ;-)

**Pull request closed without merging**
