### PR TITLE
vcat collect type

### PR DESCRIPTION
**Pull request by gustafsson**
collect doesn't recognize the common type if the arguments are of mixed types

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks. Though in light of https://github.com/JuliaLang/julia/issues/16029, I think it would be even better to do `[dfs...]` instead of calling `collect`.

**Comment by gustafsson** [comment]
@nalimilan Any comment on this? The test added in this PR currently fails on master.

**Comment by nalimilan** [comment]
Looks good. Could you add a comment before the test referring to this PR and explaining what is being tested?

**Comment by nalimilan** [comment]
Thanks!

**Pull request merged**
