### PR TITLE
remove linebreak that made README render badly

### PR DESCRIPTION
**Pull request by KristofferC**

### CODE REVIEW

**Comment by nalimilan** [comment]
There's the same problem with the line above ("with the").

**Comment by nalimilan** [comment]
BTW, could you add a line break between the stable and devel documentation? That would make it much clearer.

**Comment by KristofferC** [comment]
Could add doc badges like in https://github.com/JuliaDocs/Documenter.jl

**Comment by KristofferC** [comment]
made a suggestion how it could look

**Comment by nalimilan** [comment]
Thanks!

**Pull request merged**
