### PR TITLE
add tests for statsmodel functions

### PR DESCRIPTION
**Pull request by kleinschmidt**
This should improve the coverage of both formula.jl and statsmodel.jl (#786)

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
This looks awesome. Thanks for working on this.

**Comment by kleinschmidt** [comment]
I squashed and rebased this to master after #809 cleaned up the "Type cannot be constructed" error.  Should I merge it?

**Comment by johnmyleswhite** [comment]
I trust your judgment. Please do what you think is best.

**Comment by garborg** [comment]
Thanks, @kleinschmidt.

**Comment by kleinschmidt** [comment]
My pleasure, sorry it took so long to merge!

**Pull request merged**
