### PR TITLE
group function

### PR DESCRIPTION
**Pull request by matthieugomez**
The group function allows to combine multiple columns of a dataframe into one PooledDataArray column. A user case is to create groups based on multiple variables before fitting a model. 
The function `group` basically rewraps code from `groupby`.I'm not sure whether this functionality already exists or not.

### CODE REVIEW

**Comment by tshort** [comment]
Needs tests and docs...

**Comment by matthieugomez** [comment]
I have added tests, a doc.

Moreover
- I have renamed the function to `poolall` since it completes the `pool` function.
- I have added a skipna option : should observations with some column equal to NA grouped into a NA group?  The option defaults to true, conserving any NA in the original columns. I think it is the behavior one generally wants when fitting models. I don't know the usual name for NA options in Julia, so tell me if skipna does not sound right.

**Comment by matthieugomez** [comment]
I have updated my commit to solve a bug I spotted in `groupby`, which fails in the following case:

```R
    df = DataFrame(v1 = pool(1:1000), v2 = pool(fill(1, 1000))) 
   groupby(df, [:v1, :v2])
````

Grouping by `v1` and `v2` should give 1000 groups. However, only 255 groups are created. `pool(fill(1, 1000))` creates a PooledDataArray with refs of type `Vector{Uint8}`. This type  is not promoted for a higher type when grouping by `v1` and `v2`, while the number of groups becomes > 255. I now promote this vector to `Uint32` in all cases. I have added a test for this example.

**Comment by matthieugomez** [comment]
I think it's good to go now.

**Pull request closed without merging**
