### PR TITLE
Added keyword argument for disabling automatic intercept term in ModelMatrix

### PR DESCRIPTION
**Pull request by jlepird**
In some regularization methods, the intercept term is handled differently. One wants to penalize the magnitude of coefficients on explanatory variables, but not the intercept, as this would result in different models for data that were simply shifted vertically. 

I added a keyword argument to disable the automatic inclusion of the offset term. I set the default for backwards capability, but in my opinion we probably shouldn't include the intercept unless the user specifically asks for it, as users should probably be centering their own data first anyways.

### CODE REVIEW

**Comment by nalimilan** [comment]
The issue with the implicit intercept was discussed at length here: https://groups.google.com/d/msg/julia-stats/jXvE2S_JBds/B1_2hYv6RNkJ Specifically, @johnmyleswhite talked about not storing the intercept to ease regularization, which IIUC is the same problem as yours.

Anyway, it looks like the outcome of that discussion was that we should get rid of implicit intercepts, so it might be time do make this change. (Another quite popular suggestion was to print a warning when no intercept is present, which is likely to be a common mistake, and require people to specify `+ 0` or `-1` in those cases).

**Comment by jlepird** [comment]
Yep, it looks like that thread contained my concern.

Regardless of how we want users to specify that they want to library to handle the intercept for them, it should be up to the libraries using Dataframes to determine how they want to implement the intercept handling. 

This commit provides a temporary fix to this by allowing libraries to override the default column of one's if they want to. If we don't merge this, we should at least put a shout-out in the documentation saying that libraries can override this default by setting the modelframes .terms.intercept value to false. Currently, based on the documentation, they only approach would be to create the model matrix and then just drop the first column, but that's obviously super wasteful.

**Comment by johnmyleswhite** [comment]
Chiming in quickly:

* We need to distinguish the formula language from how we construct model matrices.
* I would prefer that the formula language make intercepts be explicit.
* I would also prefer that we not include intercepts in the model matrix, since this is memory-wasteful (although it might decrease compute-time because matrix multiply might be much faster than including the intercept manually). It's also strange if you happen to have a no-intercept model matrix around, since you then end up allocating a whole new matrix when you only want to try including an intercept.
* All that said, not including intercepts is a radical departure from how R handles things. So it's not an easy thing to make the move.

Ultimately, I think we need to have @dmbates on board with any proposed changes. He's done the vast majority of work on linear modeling in Julia.

I don't think we should encouraging users to zero-center features by default. In my mind, that's too user-unfriendly.

**Comment by jlepird** [comment]
@johnmyleswhite, you're right; I should have specified "library" instead of "user" my merge-request comment. 

For the long term, I personally would think the following would be best:
    1. Have the users specify that they want an intercept in the term with a +1.
    2. From there, pass something to the library using DataFrames telling them to handle the intercept in whatever way the library deems optimal. 

This commit addresses neither of these; I just wanted to be able to disable the automatic columns of one for a RLS library I'm working on.

**Comment by johnmyleswhite** [comment]
I'm on board with that change. The reason I bring everything else up is that I think it would be good to try to build consensus for the broader changes as soon as possible. Everything that doesn't change early on risks becoming permanent.

**Comment by quinnj** [comment]
This code has moved to https://github.com/JuliaStats/StatsModels.jl

**Pull request closed without merging**
