### PR TITLE
vcat for a single dataframe

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by nalimilan** [comment]
Why would one store data frames in a column of a data frame? Why not have a method `vcat(df[c])` instead?

**Comment by bramtayl** [comment]
Because other columns in the dataframe besides c don't get lost. This should solve #659. There's still a bug in the 0.5.0 version.

**Comment by bramtayl** [comment]
I think the 0.5 errors aren't caused by this PR. The test file I modified, cat.jl, passes. And for me, the testing errors still appear when running with unmodified DataFrames. I'm also not sure why coverage decreases. The code that I added is 100% covered.

**Comment by nalimilan** [comment]
https://github.com/JuliaStats/DataFrames.jl/issues/659 is very different: it's about `vcat(df::DataFrame...; source::Vector{Symbol})`. This PR stores data frames inside data frames, which doesn't make sense to me. Could you explain your use case?

**Comment by bramtayl** [comment]
Here's an example

```{julia}
using DataFrames

USA = DataFrame(region = ["California", "New York"],
                capital = ["Sacramento", "Albany"] )

Canada = DataFrame(region = ["Ontario", "Quebec"],
                   capital = ["Toronto", "Quebec City"] )

country = DataFrame(country = ["USA", "Canada"],
                    president = ["Obama", "Trudeau"],
                    data = [USA, Canada] )

region = vcat(country, :data)

Test.@test region == DataFrame(country = ["Canada", "Canada", "USA", "USA"],
                               president = ["Trudeau", "Trudeau", "Obama", "Obama"],
                               region = ["Ontario", "Quebec",  "California", "New York"],
                               capital = ["Toronto", "Quebec City", "Sacramento", "Albany"] )
```

**Comment by bramtayl** [comment]
The issues with 0.5 should be solved with JuliaStats/DataArrays#195

**Comment by nalimilan** [comment]
Wouldn't this classically be handled using `join`?

**Comment by bramtayl** [comment]
I guess you could do

```{julia}
delete!(country, :data)
USA[:country] = "USA"
Canada[:country] = "Canada"

result = join(vcat(USA, Canada), country, on = :country)
```

But I feel like this would be a pain, especially if you were trying to piece together many little dataframes

**Comment by nalimilan** [comment]
I don't see how it would be so painful. I'd really need to see prior art in similar libraries before adding what appears to me as a very non-standard way of doing something that's possible using standard operations.

**Comment by bramtayl** [comment]
I see what you're saying. One important use case I can think of is reading in XML, JSON, or YAML data, which is often nested in hierarchical but consistent ways. The functionality here fully covers #659 (just imagine country as a "source"). I could add methods pretty easily for a Dict of data, or separate vectors of dataframes and source names.

**Comment by nalimilan** [comment]
I think https://github.com/JuliaStats/DataFrames.jl/issues/659 is very different from this IMHO.

XML, JSON and YAML deserve consideration, but let's see concrete cases of this first. This could as well be handled by specific methods in those packages (AFAIK, they don't create data frames at all).

Anyway, let's hear what others think.

**Comment by bramtayl** [comment]
Ok, just one more example:

```{julia}
vcat(df1, df2, df3; source = ["X", "Y", "Z"], name = "source")
```
from #659

Is equivalent to, here,
```{julia}
vcat(DataFrame(data = [df1, df2, df3], source = ["X", "Y", "Z"]), :data)
```

**Comment by nalimilan** [comment]
Two concatenation operations: you've effectively demonstrated they're completely unrelated.

**Comment by bramtayl** [comment]
I don't understand what you mean by two concatenation operations? `[df1, df2, df3]` should return a vector of dataframes.

**Comment by nalimilan** [comment]
I mean it's a quite complex syntax. I don't see the point of storing data frames inside a data frame column to do that.

**Comment by bramtayl** [comment]
I guess. But when I program, everything that I can keep in a dataframe, I do keep in a dataframe. So to use #659 vcat syntax, I would have to do:

```{julia}
vcat(country[:data]..., source = country[:country])
```

**Comment by kleinschmidt** [comment]
FWIW, I'm using the vector-of-dataframes idiom a lot these days in R. Here's an example of how that can be useful: https://jofrhwld.github.io/blog/2016/05/01/many_models.html.

I'm not sure if that's exactly what's going on here, but I really like being able to nest/unnest data in this way.

**Comment by johnmyleswhite** [comment]
I think is way too weird to allow. The idea of having data frames in a column isn't strange: it's often the way that experts in relational algebra describe operations like SQL's GROUP BY. But we implement those things in a totally different way.

**Pull request closed without merging**
