### PR TITLE
Undo restriction of AbstractString to String

### PR DESCRIPTION
**Pull request by andreasnoack**
Accidentally, I also changed `AbstractString` in https://github.com/JuliaStats/DataFrames.jl/pull/957 and it caused https://github.com/JuliaStats/DataFrames.jl/issues/963. This PR should fix this.

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks, LGTM! I guess we should tag a new release too.

**Comment by tkelman** [comment]
Should probably add tests that would catch this in the future.

**Comment by nalimilan** [comment]
But that's getting harder now that we only have one `String` type in Base...

**Comment by StefanKarpinski** [comment]
For Base itself, I was planning on doing testing using `GenericString` and `LumpyString` types – the former would just wrap another string directly, using generic methods, while the "lumpy" version would fake out representing each character with a random number of bytes. Perhaps it would be good to define those in `Base.Test` so that other packages can use them for their testing.

**Comment by tkelman** [comment]
SubString is also still there, at least for a little while longer

**Pull request merged**
