### PR TITLE
make column Vector always of type Any so arbitrary vectors always can be pushed to it

### PR DESCRIPTION
**Pull request by KristofferC**
Ref https://discourse.julialang.org/t/add-a-column-of-ints-to-a-dataframe-of-strings/4976

Not sure about performance implications.

### CODE REVIEW

**Comment by nalimilan** [comment]
Thanks, but at this point changes should be made in DataTables until we backport everything. Maybe the bug is already fixed there?

**Comment by ararslan** [comment]
Can't DataTables already store vectors of any type? So whenever we get around to backporting everything this functionality will be available?

**Comment by KristofferC** [comment]
Looks like https://github.com/JuliaData/DataTables.jl/blob/38750208cc2c81ebfe6946583f52ff193182d8ed/src/datatable/datatable.jl#L73 has it fixed

**Comment by nalimilan** [comment]
Cool, thanks for checking!

**Pull request closed without merging**
