### PR TITLE
Remove remaining julia 0.3 dict syntax

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by ararslan** [comment]
That syntax isn't supported on Julia 0.4, which is causing the failures. Since there isn't a `@compat` for this, I don't think we'll be able to drop the syntax entirely until we stop supporting 0.4.

**Comment by KristofferC** [comment]
Ref https://github.com/JuliaLang/Compat.jl/issues/231 for workarounds?

**Comment by davidanthoff** [comment]
I believe all the travis and appveyor errors are not related to this PR. The travis build timed out, and two of the appveyor errors are reported elsewhere(JuliaStats/Rmath.jl#12) and the last appveyor error seems related to something else.

**Comment by davidanthoff** [comment]
Bump, who could merge this?

**Comment by ararslan** [comment]
I restarted the Travis build just to be safe. I agree the AppVeyor stuff seems unrelated.

**Comment by davidanthoff** [comment]
Excellent! Could you also tag a version?

**Comment by ararslan** [comment]
Sure thing. As with Distributions, I can do that later today if no one beats me to it.

**Comment by ararslan** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5878

**Pull request merged**
