### PR TITLE
Split grouped data frames and join by common variables.

### PR DESCRIPTION
**Pull request by bramtayl**
No chaining, I promise.

I've made two small changes:
* Added a split function which splits a grouped data frame into a data frame of data frames.
* Allowed for joining on common variables. This is what is done in `dplyr`.

See #833

### CODE REVIEW

**Comment by garborg** [comment]
Joining on implicit keys isn't going to happen -- it was allowed at one point, but it was removed (for being dangerous / causing more problems than the convenience justified, etc.) after discussion.

Could you provide an example of your use case for this `split` function?

`GroupedDataFrame`s were once made up of many small `DataFrame`s but it was much less efficient than the current state, which still has a ways to go before it's competitive with split-apply-combine in similar frameworks in other languages. Anyway, I want to understand if the current machinery could serve for your task to make sure we aren't adding extra ways to do the same thing. Thanks.

**Comment by bramtayl** [comment]
I can understand why joining on implicit keys is dangerous. With strategic use of map and reduce(vcat), it seems that split data frames could allow you to do almost anything in the split-apply-combine arsenal, but with more control than, say, `dplyr`.

**Comment by garborg** [comment]
I think we have more to do improving split-apply-combine (`groupby`-`map`-`combine` here) functionality, but what you mentioned is supported already:

```julia
# test data
julia> df = DataFrame(A = rep(1:2, 4), B = rep(1:4, 2), C = rand(8))
8x3 DataFrames.DataFrame
| Row | A | B | C        |
|-----|---|---|----------|
| 1   | 1 | 1 | 0.243176 |
| 2   | 2 | 2 | 0.21313  |
| 3   | 1 | 3 | 0.56217  |
| 4   | 2 | 4 | 0.857106 |
| 5   | 1 | 1 | 0.348625 |
| 6   | 2 | 2 | 0.869271 |
| 7   | 1 | 3 | 0.812846 |
| 8   | 2 | 4 | 0.530066 |

# split-apply-combine in one fell swoop
julia> by(df, [:A, :B], d -> DataFrame(CMin = minimum(d[:C])))
4x3 DataFrames.DataFrame
| Row | A | B | CMin     |
|-----|---|---|----------|
| 1   | 1 | 1 | 0.243176 |
| 2   | 1 | 3 | 0.56217  |
| 3   | 2 | 2 | 0.21313  |
| 4   | 2 | 4 | 0.530066 |

# split
julia> gd = groupby(df, [:A, :B])
DataFrames.GroupedDataFrame  4 groups with keys: [:A,:B]
First Group:
2x3 DataFrames.SubDataFrame{Array{Int64,1}}
| Row | A | B | C        |
|-----|---|---|----------|
| 1   | 1 | 1 | 0.243176 |
| 2   | 1 | 1 | 0.348625 |
⋮
Last Group:
2x3 DataFrames.SubDataFrame{Array{Int64,1}}
| Row | A | B | C        |
|-----|---|---|----------|
| 1   | 2 | 4 | 0.857106 |
| 2   | 2 | 4 | 0.530066 |

# apply
julia> ga = map(d -> DataFrame(CMin = minimum(d[:C])), gd)
DataFrames.GroupApplied(DataFrames.GroupedDataFrame  4 groups with keys: [:A,:B]
First Group:
2x3 DataFrames.SubDataFrame{Array{Int64,1}}
| Row | A | B | C        |
|-----|---|---|----------|
| 1   | 1 | 1 | 0.243176 |
| 2   | 1 | 1 | 0.348625 |
⋮
Last Group:
2x3 DataFrames.SubDataFrame{Array{Int64,1}}
| Row | A | B | C        |
|-----|---|---|----------|
| 1   | 2 | 4 | 0.857106 |
| 2   | 2 | 4 | 0.530066 |,DataFrames.AbstractDataFrame[1x1 DataFrames.DataFrame
| Row | CMin     |
|-----|----------|
| 1   | 0.243176 |,1x1 DataFrames.DataFrame
| Row | CMin    |
|-----|---------|
| 1   | 0.56217 |,1x1 DataFrames.DataFrame
| Row | CMin    |
|-----|---------|
| 1   | 0.21313 |,1x1 DataFrames.DataFrame
| Row | CMin     |
|-----|----------|
| 1   | 0.530066 |])

# could keep applying
...

# combine
julia> combine(ga)
4x3 DataFrames.DataFrame
| Row | A | B | CMin     |
|-----|---|---|----------|
| 1   | 1 | 1 | 0.243176 |
| 2   | 1 | 3 | 0.56217  |
| 3   | 2 | 2 | 0.21313  |
| 4   | 2 | 4 | 0.530066 |
```

**Comment by bramtayl** [comment]
Hmm, I wasn't aware you could do all that. But I feel like if I was clever enough, I could come up with a lot of things that are possible with a split data frame that aren't possible with a GroupedDataFrame. Transposes? hcats? Sampling?

**Comment by johnmyleswhite** [comment]
I think the most important consideration in this discussion is that most of the JuliaStats committers have already given up on DataFrames as a dead end. So investing energy into optimizing a data structure we're abandoning seems less than fruitful.

**Comment by bramtayl** [comment]
Why? What will people use instead?

**Comment by johnmyleswhite** [comment]
We're still figuring that out. Stay tuned for announcements after the stakeholders figure things out.

**Comment by bramtayl** [comment]
An n-dimensional data frame could be cool. Or really, just a way to put a dict-like index onto any dimension of an array.

**Comment by bramtayl** [comment]
Or a way to use multiple keys per dimension, similar to data.table

**Comment by garborg** [comment]
@bramtayl This raises some good points - that during the redesign we should explore how grouping could be composable with reshaping. And the point about sampling was good -- `GroupedDataFrame` and `GroupApplied` (well, their replacements) should at least be iterable, possible indexable (desirable, but I'm not certain it will fit with the redesign).

Re: `join_auto` -- if you know the key, it's shorter to just be explicit, if you don't `intersect(names(d1), names(d2))` is explicit, and not so onerous (also easy to derive for convenience functions in userland if really desired), so I don't think growing the API for all joins types is justified.

I'm going to close this with the note that we should be thinking about this grouping functionality during the redesign.

**Pull request closed without merging**
