### PR TITLE
Optimize RDA

### PR DESCRIPTION
**Pull request by alyst**
* Decouple XDR and ASCII formats by subclassing RDAIO type. 
* Optimize the speed and memory footprint of RDA import by buffering and "vectorizing" column data reads.
 Reading of sample 84M binary RData file on my system before the patch:
```
[~]$ julia -e "using DataFrames; @time read_rda(\"test.RData\")"
 elapsed time: 52.973835777 seconds (5705277252 bytes allocated, 50.75% gc time)
```
  after:
```
[~]$ julia -e "using DataFrames; @time read_rda(\"\test.RData\")"
elapsed time: 15.160802834 seconds (2433811160 bytes allocated, 5.08% gc time)
```
* Support NAs in character vectors.

### CODE REVIEW

**Comment by garborg** [comment]
This is exciting!
Travis is showing all test builds failing on the same test -- here's the coverage report alongside it: (https://coveralls.io/files/409339666) not familiar enough with the RDA format to tell at a glance if any of those uncovered branches would be trivial to add tests for.

**Comment by alyst** [comment]
Hopefully now it should be fixed. I've also added ASCII-format RDAs, that should improve the coverage.

**Comment by garborg** [comment]
Looks good (OSX tests are getting held up downloading deps today, but they're hanging post tests, so good to go). Thanks for your work on this, and for expanding the tests.

**Comment by dmbates** [comment]
I just posted a message on the julia-users list regarding using an embedded R in Julia, which I think will be the way to go rather than refining RDA.jl or adding data sets to the RDatasets package.  Because R is Open Source it is reasonable to expect a user who wants to read saved R data to have R installed.  Then the hard work of reading saved R data can be relegated to R and just the results pulled into Julia.

I plan to create a package under the JuliaStats group and would welcome others contributing to it.

**Comment by garborg** [comment]
That would be excellent.

Just a note that the code in `src/RDA.jl` code should stick around beyond that (somewhere) so long as `RDatasets` has .rdas.

For the original 700+ datasets in `RDatasets`, part of the choice of storage format went: if there's a factor column that really is categorical (i.e. not a bunch of unique strings that are encoded as factors due to data/habits from before R's global string cache), make sure it's saved as .rda, otherwise .csv is okay).

**Comment by alyst** [comment]
@dmbates A transparent access to R from Julia would be a killer feature indeed! But actually, Julia's native implementation of RDA reading can coexist with it in the long-term. To read some bulky R datasets into Julia one might require reading them directly, rather then occupying RAM (and swap) with both Julia's and R's representation of the data.
I'm not an expert in RDA format, but I think the current implementation is not too far away from being reasonably complete. It doesn't yet support reading UTF8 strings and some special R features like environments and packages, but the latter could be imported just the same way as we do with R lists.

**Pull request merged**
