### PR TITLE
Add an example for loading remote data with `readtable`

### PR DESCRIPTION
**Pull request by pwoolcoc**

### CODE REVIEW

**Comment by pwoolcoc** [comment]
I only changed the docs under `doc/source`, I didn't touch `docs`. I am assuming `docs` is generated from `doc/source`, but didn't know the procedure to use to generate them. If you can let me know what that is, I can regenerate `docs/io.md` and push that to this PR as well.

**Comment by johnmyleswhite** [comment]
I think we'd prefer to keep things more modular than this. Adding yet another dependency makes this package brittle IMO. It would be better to stick with the explicit `io` input formulation and have people provide `IO` objects as inputs.

**Comment by pwoolcoc** [comment]
Ah, ok. There was a placeholder there for paths starting with `http` or `ftp`, so I assumed it was a desired feature.

**Comment by johnmyleswhite** [comment]
It was once something we really wanted, but I think we're moving away from the monolithic approach to DataFrames' functionality we were taking in the past. (In part because we simply don't have enough engineering resources to maintain a large codebase.)

What do you think of making your code into a doc example that shows how to do this with the current codebase?

**Comment by pwoolcoc** [comment]
Sure, I can do that. Right in `doc/source/io.rst`? What is the procedure for generating the `.md` files from the `.rst`?

**Comment by johnmyleswhite** [comment]
I believe that's right, but other people like @cgoldammer took control of the docs a while back, so I'm not totally sure.

**Comment by nalimilan** [comment]
Is this OK to merge?

**Comment by johnmyleswhite** [comment]
@nalimilan: I think you're effectively the new DataFrames maintainer, so I think you should feel free to merge things when you see fit.

**Comment by tshort** [comment]
Don't scare him away, John:) I also think he should merge at will...

**Comment by nalimilan** [comment]
"Effectively." Knowing that data frames are a dead-end, I'm just trying to merge patches that are ready. I won't go further...

@tshort Won't this conflict with your Lapidary PR? Is that OK for you?

**Comment by tshort** [comment]
Don't worry about conflicts with my work. I already have to do some merging/rebasing.

**Comment by datnamer** [comment]
@nalimilan what should one be using then?  TypedTables.jl?

**Comment by nalimilan** [comment]
@datnamer I'm not saying that you shouldn't use DataFrames currently, but in terms of development we're looking for a more efficient approach which would offer type-stability. TypedTables is indeed a possible solution.

**Comment by datnamer** [comment]
Understood. Are there still thoughts of basing it on sqlite?

**Comment by nalimilan** [comment]
I think the point of DataFrames and similar structures is to have everything in memory as Julia structures. SQL databases will be (are) supported by other structures, ideally with a common API.

**Comment by datnamer** [comment]
Are you thinking of a table abstraction over SQL and a dataframe meta like query language, or some kind of DBAPI with plain SQL as the DSL?

**Comment by tshort** [comment]
Some ideas here:

http://juliacomputing.com/blog/2016/01/14/stats-roadmap.html

**Comment by datnamer** [comment]
Interesting thanks.

**Pull request merged**
