### PR TITLE
Document renaming multiple columns at a time

### PR DESCRIPTION
**Pull request by emilbayes**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
LGTM

**Comment by alyst** [comment]
The only minor problem is that this syntax is deprecated in 0.4, but it could be updated later.

**Comment by emilbayes** [comment]
@alyst Sorry, I didn't know. I've been using `0.3.10`. Is the `{key => value}` syntax deprecated?

**Comment by nalimilan** [comment]
@emilbayes Yes, the new syntax generalizes the special-casing of dicts which was used in 0.3:
`Dict(:old_name => :new_name, :another_old_name => :another_new_name)`

But documenting the 0.3 syntax is probably OK for now.

**Comment by alyst** [comment]
@emilbayes It's deprecated, but you still can use it in 0.4. `Dict(:a => :b)` syntax is not supported by 0.3. So I guess we just merge your fix and update the docs when 0.3 support would be dropped.

**Pull request merged**
