### PR TITLE
Do a better job deprecating read_rda

### PR DESCRIPTION
**Pull request by ararslan**
Alternative to #1056 (and borrows some code) cc @andreasnoack

### CODE REVIEW

**Comment by andreasnoack** [comment]
I've just made the same change so this shouldn't be necessary.

**Comment by ararslan** [comment]
Oh sweet, thanks! Then the Compat version bump shouldn't be necessary, right?

**Comment by andreasnoack** [comment]
It is necessary for the new `redirect_stderr` method.

**Comment by ararslan** [comment]
Oh, okay. Thanks again for cleaning up the mess I made. I really appreciate it!

**Comment by ararslan** [comment]
Have you not pushed your changes to your branch?

**Comment by andreasnoack** [comment]
Not yet. I trying to be gentle to the Travis queue. In particular, OSX seems to be a problem and since `Compat` hasn't been tagged yet, I thought it would be better to wait.

**Comment by vchuravy** [comment]
;) I love the branch name.

**Comment by ararslan** [comment]
@andreasnoack Yeah, good call. We had a bunch of PRs all at once and I think Travis got a little overwhelmed.

**Pull request closed without merging**
