### PR TITLE
Fix Warning: the no-op `transpose` fallback is deprecated warning.

### PR DESCRIPTION
**Pull request by Nectarineimp**
replace line 599 of show.jl
header = map(x->strong(string(x)), names(df)[1:width]')

with
header = map(x->strong(string(x)), reshape(names(df), 1, width))

### CODE REVIEW

**Comment by ararslan** [comment]
Hi @Nectarineimp! Did you mean to open this PR against master rather than release-0.8? It would be great if you could do master instead, that way we can cherry-pick the commit(s) to the release-0.8 branch as needed to make a patch release in the 0.8 series.

**Comment by Nectarineimp** [comment]
This is my first ever pull request, and it didn't enable to button with the default master/master dropdowns. I'd love to do this against the master since its as simple fix and eliminates something being deprecated. I will see if I can modify the pull.

**Comment by ararslan** [comment]
I don't think it's possible to modify which branch you're submitting a pull request to, so I think your best bet will be to close this one and open a new PR against master.

**Comment by Nectarineimp** [comment]
Closing so I can resubmit the correct way.

**Pull request closed without merging**
