### PR TITLE
Update StatsBase.df to dof

### PR DESCRIPTION
**Pull request by ararslan**
why is this even defined here

### CODE REVIEW

**Comment by ararslan** [comment]
We should tag a patch release once this is merged, but we'll have to cherry-pick around the nullable change.

**Comment by simonster** [comment]
This is defined here for models fit on DataFrames because we wrap them in a `DataFrameStatisticalModel`/`DataFrameRegressionModel`. We do this to allow models to be fit on DataFrames without requiring explicit package support, but while still keeping track of the mapping between coefficients and columns.

**Comment by ararslan** [comment]
@simonster Oh okay, makes sense. Thanks for the explanation!

**Comment by nalimilan** [comment]
Yes, these should be moved to a separate package together with the model frame code.

**Comment by simonster** [comment]
Maybe? From a usability perspective, it seems like it may be hard for people to figure out that to fit a GLM on a DataFrame, you need `GLM`, `DataFrames`, and then some other package that makes them talk to each other.

**Comment by nalimilan** [comment]
We could still reexport it by default. The idea is 1) to shrink the large code base of Data Frames, and 2) allow fitting models from alternative data sources (TypedTables, databases...).

**Comment by ararslan** [comment]
Or perhaps GLM could reexport it?

**Comment by nalimilan** [comment]
Possibly, but that would mean adding this to every modeling package, which are more numerous than data sources.

**Comment by ararslan** [comment]
Ah yeah. Well, I can start the process of migration... Repo name? StatModels.jl, in keeping with the name of the file in which this stuff is defined here? That's pretty general though.

**Comment by nalimilan** [comment]
The name needs to be general since that's a general framework. StatModels isn't bad.

Though before doing that work, make sure everybody agrees with that plan by asking for comments somewhere. I think I remember some opposition.

Cc: @dmbates @kleinschmidt @andreasnoack

**Comment by ararslan** [comment]
Oh sure, I wouldn't take anything out of here before getting comments. Also cc @johnmyleswhite.

If we're going to do this I also think it would be a good time to rethink how formulas are specified. It would be nice if base Julia could stop making a special case to parse ~ as an infix macro for the sake of formulas. Doug brought up alternative syntax on the mailing list, wherein he proposed using pairs instead. Anyway, something to think about when we get there.

**Comment by kleinschmidt** [comment]
Might make sense to discuss this under #1018...

**Pull request merged**
