### PR TITLE
Accept AbstractVector in describe(), fixes #781

### LINKED ISSUE #781: describe fails with a DataFrame converted from an array
```
julia> df=convert(DataFrame,ones(2,2));
julia> describe(df)
x1
ERROR: `describe` has no method matching describe(::TTY, ::Array{Float64,1})
 in describe at /home/jao/.julia/v0.3/DataFrames/src/abstractdataframe/abstractdataframe.jl:401
 in describe at /home/jao/.julia/v0.3/DataFrames/src/abstractdataframe/abstractdataframe.jl:397
```
My julia version is 0.3.6

### PR DESCRIPTION
**Pull request by jlep**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Does this pass tests locally? A priori this change seems reasonable, but it would be good to confirm that you don't hit any missing method errors.

In that regard, you should probably add a test to confirm that this works for an abstract vector.

**Comment by jlep** [comment]
I added tests for describe() that output to /dev/null (or nul on windows) to avoid cluttering stdout/stderr when running tests. Hopefully this isn't too brittle... it's also used in https://github.com/JuliaLang/julia/blob/master/base/process.jl to allow redirecting to /dev/null with |> DevNull.

All tests pass locally. Apparently travis has some problems but it seems to be due to something else.

**Comment by garborg** [comment]
Not surprised by the failure on 0.4. I was hoping to clean things up on 0.4 yesterday (there have been a lot of changes to 0.4 recently), but there were a couple upstream package fixes to make first, and there was an outstanding 0.4 bug that has since been fixed. Hoping to get to it tomorrow.

**Comment by garborg** [comment]
Thanks @jlep! These commits just got merged in #785 (which added a commit for a syntax issue your new tests uncovered).

**Comment by jlep** [comment]
Awesome!

**Pull request closed without merging**
