### PR TITLE
Fix passing UTF8String to readtable's eltypes argument

### PR DESCRIPTION
**Pull request by nalimilan**
This really needs to remain UTF8String on Julia 0.4.

Fixes https://github.com/JuliaStats/DataFrames.jl/issues/969.

### CODE REVIEW

**Comment by nalimilan** [comment]
That porting process is trickier than it seemed. Actually, instead of rushing towards `String`, what we really need to do is keep the existing `ASCIIString`/`UTF8String` and simply use the new aliases from Compat. I even wonder whether Compat should provide `String` at all on 0.4 since it's type-unstable; it should probably be called `ByteString` instead to be less appealing.

@StefanKarpinski @yuyichao What do you think?

**Comment by yuyichao** [comment]
> I even wonder whether `Compat` should provide `String` at all on 0.4 since it's type-unstable; it should probably be called `ByteString` instead to be less appealing.

I agree it should be better documented that replacing `{ASCII,UTF8}String` with `String` is not the correct thing to do in most cases. If feels a little weird if the 0.5 syntax can't be used anywhere though (which is partly the nature of the change......) so I think exporting `ByteString` as `String` on 0.4 is the best compromise now.

In this sense, the original commit that exports `UTF8String` as `String` is better. Exporting `ByteString` as `String` was done since it does cover much more usage than `UTF8String` but maybe it encourages people who didn't test the package thoroughly on 0.4 to use it incorrectly.....

**Comment by nalimilan** [comment]
What's the advantage of exporting `ByteString` as `String`? Shouldn't people use `AbstractString` in most cases where they want a loose typing?

**Comment by nalimilan** [comment]
I've made a PR at https://github.com/JuliaLang/Compat.jl/pull/205.

**Comment by nalimilan** [comment]
Two more reports today, I'm going to merge this.

**Pull request merged**
