### PR TITLE
Updates for Documenter.jl syntax changes

### PR DESCRIPTION
**Pull request by MichaelHatherly**
See https://github.com/MichaelHatherly/Documenter.jl/pull/51 for details.

### CODE REVIEW

**Comment by nalimilan** [comment]
I trust you that this is correct, but let's ask @tshort anyway.

**Comment by MichaelHatherly** [comment]
I was doing quite a few of these at once, so another set of eyes would be good.

**Comment by tshort** [comment]
Looks good to me...

**Comment by nalimilan** [comment]
Damn, we completely forgot this PR, and the homepage of the manual is currently broken. Would you mind rebasing this?

**Comment by MichaelHatherly** [comment]
Whoops, will do shortly.

**Comment by MichaelHatherly** [comment]
Also took the chance to switch to the new HTML output.

**Comment by nalimilan** [comment]
Great, thanks!

**Comment by nalimilan** [comment]
Do we need to run a command to update the online manual?

**Comment by MichaelHatherly** [comment]
Nope, already done: https://juliastats.github.io/DataFrames.jl/latest/

**Pull request merged**
