### PR TITLE
Cleaned up MkDocs after conversion from Sphinx

### PR DESCRIPTION
**Pull request by cgoldammer**
@tshort, this overwhelmingly consisted of changing the headers and the code markdown. I've done some other minor changes, e.g removed the "indexing" from "joins and indexing" because it wasn't talked about.

In later PRs, I'll add content, and I will also go through the existing content to make sure it's all still relevant.

### CODE REVIEW

**Comment by tshort** [comment]
Thanks, Christian!

**Comment by johnmyleswhite** [comment]
Very nice work!

**Comment by johnmyleswhite** [comment]
Christian, I gave you commit access to this repo to help remove friction when working on the docs going forward. As goes without saying, with great power comes great responsibility. :)

**Comment by cgoldammer** [comment]
@johnmyleswhite, thanks! I'll use my new-found powers wisely.

**Pull request merged**
