### PR TITLE
Allow single element strings for `readtable` separator

### PR DESCRIPTION
**Pull request by jakebolewski**

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Looks good to me. Squash and merge?

**Comment by nalimilan** [comment]
Any special reason why you need this? Wouldn't it be simpler to require people to pass a `Char` or extract it themselves from a string? Doesn't look like it's very common to pass either type without knowing it in advance.

**Comment by jakebolewski** [comment]
No, it was the first thing I tried.  Gave a no method error (not the best
from a usability perspective).  In cases like this where performance does
not matter at all, why not be permissive in the argument types you can
handle?

**Comment by johnmyleswhite** [comment]
FWIW, I think the main argument for allowing strings is that future parsers need to support multi-character separators.

**Comment by garborg** [comment]
I'll take your word for it, but I've had to deal with some funny encodings but never multi-character (outside of whitespace, which isn't relevant here), so I'd rather add support for being fast enough to be worth using before adding too many obscure features. 

For another critical issue for standard formats, see #672 -- there's no way to keep `readtable` from mangling strings even when you know how quote characters were escaped -- haven't checked, but do you know if `CSVReaders.jl` has the same issue?

**Comment by johnmyleswhite** [comment]
@garborg, you may be right that multicharacter support is so low-pri as to be not worth working on. It turns out the example I had in mind doesn't use multicharacter separators, just weird separators (`|`).

CSVReaders.jl looks like it'll have the same problem: https://github.com/johnmyleswhite/CSVReaders.jl/blob/da4ceee98f2a740f2023830d5bc9ee2daeb639d1/src/03_process_escape.jl

I believe the reason we're hitting those problems is that I've tried too hard to deal with people not knowing how escaping would work, so we try to handle multiple kinds of escapes simultaneously.

I do really want us to have a higher performance CSV parser. Right now CSVReaders.jl is slower than DataFrames, but uses a lot less memory. But it has some correctness issues that I haven't fully resolved because it doesn't retain the string contents of fields that were successfully parsed in early rows, which means that a column that contains something like `[true, 1, 1.1, "foo"]` will get parsed into something like `["1.0", "1.0", "1.1", "foo"]`.

If you'd be up for it, I'd love to do a hackathon to get CSVReaders to a point where we could rip out the custom parsing from DataFrames and use CSVReaders alone. That would also put us in a place where we don't have separate codebases for `readdlm` and `readtable`, which really bums me out.

**Comment by garborg** [comment]
@johnmyleswhite I'd really like to use CSVReaders for DataFrames, too -- it's clearly a much cleaner chunk of code. The correctness issue sounds tricky (for the streaming/not-mmapping + column eltypes not provided case).

**Comment by johnmyleswhite** [comment]
I don't think there's a clear solution. One thing that helps a bit is to parse Bool after numbers, but then you don't fail as early as you might and waste memory; in practice, I think the best you can do is to try to identify lossy translations and error out saying that column types need to be specified.

**Comment by garborg** [comment]
That sounds like a great place to start.

**Comment by nalimilan** [comment]
@jakebolewski Not sure, but there's a maintenance cost of supporting all possible meaningful types for arguments. People need to understand the difference between character and string in Julia anyways for many other things. Normally, the method error will highlight the argument that doesn't match, and you should easily see that you should pass a `Char`. Again, that's going to be a pretty common experience in Julia.

That said, I often advocate supporting a wider range of input types, so I'm not sure what the rule should be. I wonder whether there should be a way of saying "this argument can be either an `AbstractString` or a `Char`, but automatically convert it to a `Char` so that I don't have to handle the string case explicitly"; something like `separator::Union(Char,String) as Char = ','`. That would alleviate the burden of argument handling.

**Comment by quinnj** [comment]
`readtable` `writetable` are now deprecated

**Pull request closed without merging**
