### PR TITLE
Fix tests with Julia 0.5

### PR DESCRIPTION
**Pull request by nalimilan**
Looks like this also fixed tests for 0.3, no idea why...

### CODE REVIEW

**Comment by alyst** [comment]
Are there any tests for ordering using a vector of different functions? Would `Vector{S}`, `S<:Function` declaration still work in that case?

**Comment by nalimilan** [comment]
> Are there any tests for ordering using a vector of different functions? Would Vector{S}, S<:Function declaration still work in that case?

I don't know whether it's correctly tested, but it should work:
```julia

julia> f{T<:Function}(x::AbstractVector{T}) = x
f([meg (generic function with 1 method)

julia> f([mean,sum])
2-element Array{Function,1}:
 mean
 sum 
```

**Comment by alyst** [comment]
@nalimilan Ah, right. So the updated declaration would potentially optimize the code when all functions are the same.

**Comment by nalimilan** [comment]
> @nalimilan Ah, right. So the updated declaration would potentially optimize the code when all functions are the same.

The declaration wouldn't change anything AFAIK (we could also completely get rid of type assertions), but indeed the new Julia makes passing functions more efficient. I'm not sure whether the fact that all functions are the same would make a difference or not.

**Comment by alyst** [comment]
I thought in 0.5 each function (e.g. `mean`) would have its own unique type, so if `T`/`S` is resolved to this type, julia might do some call optimizations.

**Comment by nalimilan** [comment]
Yes, but that might also happen even when an array contains different functions, if we pass each function individually to another one, so that type inference is applied separately. We'd have to check that.

**Comment by nalimilan** [comment]
OK to merge? This makes all PRs fail the tests.

**Comment by alyst** [comment]
LGTM

**Pull request merged**
