### PR TITLE
Prevent a BoundsError

### PR DESCRIPTION
**Pull request by eccmsilva**
I triggered a BoundsError here, when loading a severely corrupted file.

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
Good catch. Thanks!

**Comment by garborg** [comment]
Good catch, thanks!

For reviewers, the change has our tests failing (a test needed to be changed, too) -- let's try to check CI failure logs.

@eccmsilva An easy way remove some friction from reviewing is to run `Pkg.test("DataFrames")` locally before making the PR so you know it's at least passing tests on whatever versions of Julia you have installed locally.

**Comment by eccmsilva** [comment]
Thanks @garborg, that's great advice and I will keep that in mind for the future.

**Comment by garborg** [comment]
Great. For the record, wasn't an issue on your end -- we as reviewers have just been through periods where Travis had a lot of bogus or unrelated failures where we relied a bit much on judgment calls on whether the PR could have caused breakage.

**Pull request merged**
